--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 01/06/2020 14:32:34
-- Server version: 8.0.19
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE loteriadb;

--
-- Drop table `tbjugadadetalle`
--
DROP TABLE IF EXISTS tbjugadadetalle;

--
-- Drop table `tbjugada`
--
DROP TABLE IF EXISTS tbjugada;

--
-- Drop table `tbticketheader`
--
DROP TABLE IF EXISTS tbticketheader;

--
-- Drop table `tbusuarios`
--
DROP TABLE IF EXISTS tbusuarios;

--
-- Drop table `tbsucursales`
--
DROP TABLE IF EXISTS tbsucursales;

--
-- Drop table `tbsorteosresultados`
--
DROP TABLE IF EXISTS tbsorteosresultados;

--
-- Drop table `tbsorteos`
--
DROP TABLE IF EXISTS tbsorteos;

--
-- Drop table `tbjuegos`
--
DROP TABLE IF EXISTS tbjuegos;

--
-- Set default database
--
USE loteriadb;

--
-- Create table `tbjuegos`
--
CREATE TABLE tbjuegos (
  jgo_Id INT NOT NULL AUTO_INCREMENT,
  jgo_Descripcion VARCHAR(50) DEFAULT NULL,
  jgo_CantNumeros INT DEFAULT NULL,
  jgo_MinNumero INT DEFAULT NULL,
  jgo_MaxNumero INT DEFAULT NULL,
  jgo_ApuestaMin INT DEFAULT NULL,
  jgo_Imagen LONGBLOB DEFAULT NULL,
  PRIMARY KEY (jgo_Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `tbsorteos`
--
CREATE TABLE tbsorteos (
  sort_Id INT NOT NULL AUTO_INCREMENT,
  jgo_Id INT DEFAULT NULL,
  PRIMARY KEY (sort_Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE tbsorteos 
  ADD CONSTRAINT FK_SorteoJuego FOREIGN KEY (jgo_Id)
    REFERENCES tbjuegos(jgo_Id);

--
-- Create table `tbsorteosresultados`
--
CREATE TABLE tbsorteosresultados (
  sres_id INT NOT NULL AUTO_INCREMENT,
  sort_id INT NOT NULL,
  sres_Numero INT NOT NULL,
  PRIMARY KEY (sres_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE tbsorteosresultados 
  ADD CONSTRAINT TbSorteosResultados_Sorteo FOREIGN KEY (sort_id)
    REFERENCES tbsorteos(sort_Id);

--
-- Create table `tbsucursales`
--
CREATE TABLE tbsucursales (
  codigo INT NOT NULL AUTO_INCREMENT,
  RTN INT NOT NULL,
  direccion VARCHAR(255) DEFAULT NULL,
  nombreSucursal VARCHAR(255) DEFAULT NULL,
  responsable VARCHAR(255) DEFAULT NULL,
  imagen LONGBLOB DEFAULT NULL,
  PRIMARY KEY (codigo)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `tbusuarios`
--
CREATE TABLE tbusuarios (
  User_Id INT NOT NULL AUTO_INCREMENT,
  User_Name VARCHAR(50) NOT NULL,
  User_Password VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  User_Role VARCHAR(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  Suc_Codigo INT DEFAULT NULL,
  PRIMARY KEY (User_Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE tbusuarios 
  ADD CONSTRAINT tbUsuarios_Sucursal FOREIGN KEY (Suc_Codigo)
    REFERENCES tbsucursales(codigo);

--
-- Create table `tbticketheader`
--
CREATE TABLE tbticketheader (
  tkhe_Id INT NOT NULL AUTO_INCREMENT,
  suc_Id INT NOT NULL,
  sort_Id INT NOT NULL,
  tkhe_FechaVenta DATETIME NOT NULL,
  tkhe_SerialNumber VARCHAR(15) NOT NULL,
  PRIMARY KEY (tkhe_Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 33,
AVG_ROW_LENGTH = 512,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE tbticketheader 
  ADD CONSTRAINT FK_HeaderSorteo FOREIGN KEY (sort_Id)
    REFERENCES tbsorteos(sort_Id);

--
-- Create foreign key
--
ALTER TABLE tbticketheader 
  ADD CONSTRAINT tbticketheader_ibfk_1 FOREIGN KEY (suc_Id)
    REFERENCES tbsucursales(codigo);

--
-- Create table `tbjugada`
--
CREATE TABLE tbjugada (
  jda_id INT NOT NULL AUTO_INCREMENT,
  tkhe_Id INT NOT NULL,
  jgo_Id INT NOT NULL,
  jda_Apuesta INT NOT NULL,
  jdadet_Id INT NOT NULL,
  PRIMARY KEY (jda_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 47,
AVG_ROW_LENGTH = 390,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE tbjugada 
  ADD CONSTRAINT FK_tbjugada_tkhe_Id FOREIGN KEY (tkhe_Id)
    REFERENCES tbticketheader(tkhe_Id);

--
-- Create foreign key
--
ALTER TABLE tbjugada 
  ADD CONSTRAINT tbjugada_ibfk_1 FOREIGN KEY (jgo_Id)
    REFERENCES tbjuegos(jgo_Id);

--
-- Create table `tbjugadadetalle`
--
CREATE TABLE tbjugadadetalle (
  jdet_id INT NOT NULL AUTO_INCREMENT,
  jda_id INT NOT NULL,
  jdet_Numero INT NOT NULL,
  PRIMARY KEY (jdet_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 83,
AVG_ROW_LENGTH = 218,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE tbjugadadetalle 
  ADD CONSTRAINT tbjugadadetalle_ibfk_1 FOREIGN KEY (jda_id)
    REFERENCES tbjugada(jda_id);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;