package Modelo;
// Generated 07-may-2020 20:54:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tbjugada generated by hbm2java
 */
public class Tbjugada  implements java.io.Serializable {


     private Integer jdaId;
     private Tbjuegos tbjuegos;
     private Tbticketheader tbticketheader;
     private int jdaApuesta;
     private int jdadetId;
     private Set tbjugadadetalles = new HashSet(0);

    public Tbjugada() {
    }

	
    public Tbjugada(Tbjuegos tbjuegos, Tbticketheader tbticketheader, int jdaApuesta, int jdadetId) {
        this.tbjuegos = tbjuegos;
        this.tbticketheader = tbticketheader;
        this.jdaApuesta = jdaApuesta;
        this.jdadetId = jdadetId;
    }
    public Tbjugada(Tbjuegos tbjuegos, Tbticketheader tbticketheader, int jdaApuesta, int jdadetId, Set tbjugadadetalles) {
       this.tbjuegos = tbjuegos;
       this.tbticketheader = tbticketheader;
       this.jdaApuesta = jdaApuesta;
       this.jdadetId = jdadetId;
       this.tbjugadadetalles = tbjugadadetalles;
    }
   
    public Integer getJdaId() {
        return this.jdaId;
    }
    
    public void setJdaId(Integer jdaId) {
        this.jdaId = jdaId;
    }
    public Tbjuegos getTbjuegos() {
        return this.tbjuegos;
    }
    
    public void setTbjuegos(Tbjuegos tbjuegos) {
        this.tbjuegos = tbjuegos;
    }
    public Tbticketheader getTbticketheader() {
        return this.tbticketheader;
    }
    
    public void setTbticketheader(Tbticketheader tbticketheader) {
        this.tbticketheader = tbticketheader;
    }
    public int getJdaApuesta() {
        return this.jdaApuesta;
    }
    
    public void setJdaApuesta(int jdaApuesta) {
        this.jdaApuesta = jdaApuesta;
    }
    public int getJdadetId() {
        return this.jdadetId;
    }
    
    public void setJdadetId(int jdadetId) {
        this.jdadetId = jdadetId;
    }
    public Set getTbjugadadetalles() {
        return this.tbjugadadetalles;
    }
    
    public void setTbjugadadetalles(Set tbjugadadetalles) {
        this.tbjugadadetalles = tbjugadadetalles;
    }




}


