package Modelo;
// Generated 01-jun-2020 14:41:13 by Hibernate Tools 4.3.1


import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.HashSet;
import java.util.Set;
import javafx.beans.property.SimpleObjectProperty;
import javafx.embed.swing.SwingFXUtils;
import javafx.scene.image.Image;
import javax.imageio.ImageIO;

/**
 * Tbjuegos generated by hbm2java
 */
public class Tbjuegos  implements java.io.Serializable {


     private Integer jgoId;
     private String jgoDescripcion;
     private Integer jgoCantNumeros;
     private Integer jgoMinNumero;
     private Integer jgoMaxNumero;
     private Integer jgoApuestaMin;
     private byte[] jgoImagen;
     private Set tbjugadas = new HashSet(0);
     private Set tbsorteoses = new HashSet(0);
     private SimpleObjectProperty imageView;

    public Tbjuegos() {
    }

    public Tbjuegos(String jgoDescripcion, Integer jgoCantNumeros, Integer jgoMinNumero, Integer jgoMaxNumero, Integer jgoApuestaMin, byte[] jgoImagen, Set tbjugadas, Set tbsorteoses) {
       this.jgoDescripcion = jgoDescripcion;
       this.jgoCantNumeros = jgoCantNumeros;
       this.jgoMinNumero = jgoMinNumero;
       this.jgoMaxNumero = jgoMaxNumero;
       this.jgoApuestaMin = jgoApuestaMin;
       this.jgoImagen = jgoImagen;
       this.tbjugadas = tbjugadas;
       this.tbsorteoses = tbsorteoses;
    }
   
    public Integer getJgoId() {
        return this.jgoId;
    }
    
    public void setJgoId(Integer jgoId) {
        this.jgoId = jgoId;
    }
    public String getJgoDescripcion() {
        return this.jgoDescripcion;
    }
    
    public void setJgoDescripcion(String jgoDescripcion) {
        this.jgoDescripcion = jgoDescripcion;
    }
    public Integer getJgoCantNumeros() {
        return this.jgoCantNumeros;
    }
    
    public void setJgoCantNumeros(Integer jgoCantNumeros) {
        this.jgoCantNumeros = jgoCantNumeros;
    }
    public Integer getJgoMinNumero() {
        return this.jgoMinNumero;
    }
    
    public void setJgoMinNumero(Integer jgoMinNumero) {
        this.jgoMinNumero = jgoMinNumero;
    }
    public Integer getJgoMaxNumero() {
        return this.jgoMaxNumero;
    }
    
    public void setJgoMaxNumero(Integer jgoMaxNumero) {
        this.jgoMaxNumero = jgoMaxNumero;
    }
    public Integer getJgoApuestaMin() {
        return this.jgoApuestaMin;
    }
    
    public void setJgoApuestaMin(Integer jgoApuestaMin) {
        this.jgoApuestaMin = jgoApuestaMin;
    }
    public byte[] getJgoImagen() {
        return this.jgoImagen;
    }
    
    public void setJgoImagen(byte[] jgoImagen) {
        this.jgoImagen = jgoImagen;
    }
    public Set getTbjugadas() {
        return this.tbjugadas;
    }
    
    public void setTbjugadas(Set tbjugadas) {
        this.tbjugadas = tbjugadas;
    }
    public Set getTbsorteoses() {
        return this.tbsorteoses;
    }
    
    public void setTbsorteoses(Set tbsorteoses) {
        this.tbsorteoses = tbsorteoses;
    }

    public Image getImageView() {
        Image img = new Image(new ByteArrayInputStream(jgoImagen));        
        return img;        
    }


    public void setImageView(Image image) {  
        if (image == null) {
            setJgoImagen("0".getBytes());
            return;
        }

        BufferedImage bImage = SwingFXUtils.fromFXImage(image, null);
        ByteArrayOutputStream stream = new ByteArrayOutputStream();

        try {
            ImageIO.write(bImage, "png", stream);
            byte[] bytes  = stream.toByteArray();
            stream.close();
            setJgoImagen(bytes);
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }

        //imageView.set(image);
    }

    public SimpleObjectProperty imageViewProperty() {   
        return imageView;
    }    


}


