package Modelo;
// Generated 01-may-2020 21:08:17 by Hibernate Tools 4.3.1



/**
 * Tbsorteosresultados generated by hbm2java
 */
public class Tbsorteosresultados  implements java.io.Serializable {


     private Integer sresId;
     private Tbsorteos tbsorteos;
     private int sresNumero;

    public Tbsorteosresultados() {
    }

    public Tbsorteosresultados(Tbsorteos tbsorteos, int sresNumero) {
       this.tbsorteos = tbsorteos;
       this.sresNumero = sresNumero;
    }
   
    public Integer getSresId() {
        return this.sresId;
    }
    
    public void setSresId(Integer sresId) {
        this.sresId = sresId;
    }
    public Tbsorteos getTbsorteos() {
        return this.tbsorteos;
    }
    
    public void setTbsorteos(Tbsorteos tbsorteos) {
        this.tbsorteos = tbsorteos;
    }
    public int getSresNumero() {
        return this.sresNumero;
    }
    
    public void setSresNumero(int sresNumero) {
        this.sresNumero = sresNumero;
    }




}


