package Modelo;
// Generated 07-may-2020 20:54:24 by Hibernate Tools 4.3.1



/**
 * Tbsorteosresultados generated by hbm2java
 */
public class Tbsorteosresultados  implements java.io.Serializable {


     private int sresId;
     private Tbsorteos tbsorteos;
     private int sresNumero;

    public Tbsorteosresultados() {
    }

    public Tbsorteosresultados(int sresId, Tbsorteos tbsorteos, int sresNumero) {
       this.sresId = sresId;
       this.tbsorteos = tbsorteos;
       this.sresNumero = sresNumero;
    }
   
    public int getSresId() {
        return this.sresId;
    }
    
    public void setSresId(int sresId) {
        this.sresId = sresId;
    }
    public Tbsorteos getTbsorteos() {
        return this.tbsorteos;
    }
    
    public void setTbsorteos(Tbsorteos tbsorteos) {
        this.tbsorteos = tbsorteos;
    }
    public int getSresNumero() {
        return this.sresNumero;
    }
    
    public void setSresNumero(int sresNumero) {
        this.sresNumero = sresNumero;
    }




}


