package Modelo;
// Generated 01-jun-2020 14:41:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tbsorteos generated by hbm2java
 */
public class Tbsorteos  implements java.io.Serializable {


     private Integer sortId;
     private Tbjuegos tbjuegos;
     private Set tbsorteosresultadoses = new HashSet(0);
     private Set tbticketheaders = new HashSet(0);

    public Tbsorteos() {
    }

    public Tbsorteos(Tbjuegos tbjuegos, Set tbsorteosresultadoses, Set tbticketheaders) {
       this.tbjuegos = tbjuegos;
       this.tbsorteosresultadoses = tbsorteosresultadoses;
       this.tbticketheaders = tbticketheaders;
    }
   
    public Integer getSortId() {
        return this.sortId;
    }
    
    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }
    public Tbjuegos getTbjuegos() {
        return this.tbjuegos;
    }
    
    public void setTbjuegos(Tbjuegos tbjuegos) {
        this.tbjuegos = tbjuegos;
    }
    public Set getTbsorteosresultadoses() {
        return this.tbsorteosresultadoses;
    }
    
    public void setTbsorteosresultadoses(Set tbsorteosresultadoses) {
        this.tbsorteosresultadoses = tbsorteosresultadoses;
    }
    public Set getTbticketheaders() {
        return this.tbticketheaders;
    }
    
    public void setTbticketheaders(Set tbticketheaders) {
        this.tbticketheaders = tbticketheaders;
    }




}


