package Modelo;
// Generated 01-may-2020 21:08:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tbsucursales generated by hbm2java
 */
public class Tbsucursales  implements java.io.Serializable {


     private int codigo;
     private int rtn;
     private String direccion;
     private String nombreSucursal;
     private String responsable;
     private byte[] imagen;
     private Set tbticketheaders = new HashSet(0);

    public Tbsucursales() {
    }

	
    public Tbsucursales(int codigo, int rtn) {
        this.codigo = codigo;
        this.rtn = rtn;
    }
    public Tbsucursales(int codigo, int rtn, String direccion, String nombreSucursal, String responsable, byte[] imagen, Set tbticketheaders) {
       this.codigo = codigo;
       this.rtn = rtn;
       this.direccion = direccion;
       this.nombreSucursal = nombreSucursal;
       this.responsable = responsable;
       this.imagen = imagen;
       this.tbticketheaders = tbticketheaders;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public int getRtn() {
        return this.rtn;
    }
    
    public void setRtn(int rtn) {
        this.rtn = rtn;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getNombreSucursal() {
        return this.nombreSucursal;
    }
    
    public void setNombreSucursal(String nombreSucursal) {
        this.nombreSucursal = nombreSucursal;
    }
    public String getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(String responsable) {
        this.responsable = responsable;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }
    public Set getTbticketheaders() {
        return this.tbticketheaders;
    }
    
    public void setTbticketheaders(Set tbticketheaders) {
        this.tbticketheaders = tbticketheaders;
    }




}


