package Modelo;
// Generated 01-may-2020 21:08:17 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tbticketheader generated by hbm2java
 */
public class Tbticketheader  implements java.io.Serializable {


     private Integer tkheId;
     private Tbsorteos tbsorteos;
     private Tbsucursales tbsucursales;
     private Date tkheFechaVenta;
     private String tkheSerialNumber;
     private Set tbjugadas = new HashSet(0);

    public Tbticketheader() {
    }

	
    public Tbticketheader(Tbsorteos tbsorteos, Tbsucursales tbsucursales, Date tkheFechaVenta, String tkheSerialNumber) {
        this.tbsorteos = tbsorteos;
        this.tbsucursales = tbsucursales;
        this.tkheFechaVenta = tkheFechaVenta;
        this.tkheSerialNumber = tkheSerialNumber;
    }
    public Tbticketheader(Tbsorteos tbsorteos, Tbsucursales tbsucursales, Date tkheFechaVenta, String tkheSerialNumber, Set tbjugadas) {
       this.tbsorteos = tbsorteos;
       this.tbsucursales = tbsucursales;
       this.tkheFechaVenta = tkheFechaVenta;
       this.tkheSerialNumber = tkheSerialNumber;
       this.tbjugadas = tbjugadas;
    }
   
    public Integer getTkheId() {
        return this.tkheId;
    }
    
    public void setTkheId(Integer tkheId) {
        this.tkheId = tkheId;
    }
    public Tbsorteos getTbsorteos() {
        return this.tbsorteos;
    }
    
    public void setTbsorteos(Tbsorteos tbsorteos) {
        this.tbsorteos = tbsorteos;
    }
    public Tbsucursales getTbsucursales() {
        return this.tbsucursales;
    }
    
    public void setTbsucursales(Tbsucursales tbsucursales) {
        this.tbsucursales = tbsucursales;
    }
    public Date getTkheFechaVenta() {
        return this.tkheFechaVenta;
    }
    
    public void setTkheFechaVenta(Date tkheFechaVenta) {
        this.tkheFechaVenta = tkheFechaVenta;
    }
    public String getTkheSerialNumber() {
        return this.tkheSerialNumber;
    }
    
    public void setTkheSerialNumber(String tkheSerialNumber) {
        this.tkheSerialNumber = tkheSerialNumber;
    }
    public Set getTbjugadas() {
        return this.tbjugadas;
    }
    
    public void setTbjugadas(Set tbjugadas) {
        this.tbjugadas = tbjugadas;
    }




}


